language: csharp
solution: ./SeleniumTravisIntegration/SeleniumTravisIntegration.sln
install:
  - nuget restore ./SeleniumTravisIntegrationSeleniumTravisIntegration.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ./SeleniumTravisIntegration/SeleniumTravisIntegration.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./SeleniumTravisIntegration/GoogleBrowser/bin/Release/GoogleBrowser.dll